version: "3.8"

services:
  augustin-db:
    container_name: augustin-db
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  augustin:
    container_name: augustin
    build:
      context: .
      dockerfile: Dockerfile.production
    command: "./app -prod"
    depends_on:
      augustin-db:
        condition: service_healthy
    links:
      - augustin-db
    ports:
      - "3000:3000"

volumes:
  dbdata:
