basePath: /api/
definitions:
  pgtype.Float4:
    properties:
      float32:
        type: number
      valid:
        type: boolean
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Int4:
    properties:
      int32:
        type: integer
      valid:
        type: boolean
    type: object
  pgtype.Int8:
    properties:
      int64:
        type: integer
      valid:
        type: boolean
    type: object
  pgtype.Text:
    properties:
      string:
        type: string
      valid:
        type: boolean
    type: object
  pgtype.Timestamp:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        description: Time zone will be ignored when encoding to PostgreSQL.
        type: string
      valid:
        type: boolean
    type: object
  structs.Payment:
    properties:
      amount:
        $ref: '#/definitions/pgtype.Float4'
      id:
        $ref: '#/definitions/pgtype.Int8'
      receiver:
        $ref: '#/definitions/pgtype.Int4'
      sender:
        $ref: '#/definitions/pgtype.Int4'
      timestamp:
        $ref: '#/definitions/pgtype.Timestamp'
      type:
        $ref: '#/definitions/pgtype.Int4'
    type: object
  structs.PaymentType:
    properties:
      id:
        $ref: '#/definitions/pgtype.Int4'
      name:
        $ref: '#/definitions/pgtype.Text'
    type: object
  structs.Setting:
    properties:
      color:
        type: string
      logo:
        type: string
      price:
        type: number
    type: object
  structs.Vendor:
    properties:
      credit:
        type: number
      id-number:
        type: string
      qrcode:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This swagger describes every endpoint of this project.
  license:
    name: GNU Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  termsOfService: http://swagger.io/terms/
  title: Augustin Swagger
  version: 0.0.1
paths:
  /hello/:
    get:
      consumes:
      - application/json
      description: Return HelloWorld as sample API call
      produces:
      - application/json
      responses: {}
      summary: Return HelloWorld
      tags:
      - core
  /payments:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Payment'
            type: array
      summary: Get all payments
      tags:
      - core
    post:
      consumes:
      - application/json
      description: '{"Payments":[{"Sender": 1, "Receiver":1, "Type":1,"Amount":1.00]}'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.PaymentType'
            type: array
      summary: Create a set of payments
      tags:
      - core
  /settings/:
    get:
      consumes:
      - application/json
      description: Return settings about the web-shop
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Setting'
            type: array
      summary: Return settings
      tags:
      - core
  /vendor/:
    get:
      consumes:
      - application/json
      description: Return information for the vendor
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Vendor'
            type: array
      summary: Return vendor information
      tags:
      - core
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
