basePath: /swagger/
definitions:
  handlers.Setting:
    properties:
      color:
        type: string
      logo:
        type: string
      price:
        type: number
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: 0.0.1
paths:
  /settings:
    get:
      consumes:
      - application/json
      description: get settings
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Setting'
            type: array
      summary: List settings
      tags:
      - settings
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
