on:
    push:
        branches:
            - master
            - main
    pull_request:
name: tester
jobs:
  Gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: cd app && go build -o ../build/ 

      - name: Test
        run: cd app && go test
