on:
  push:
    branches:
      - master
      - main
  pull_request:
name: tester
jobs:
  Gotest:
    runs-on: ubuntu-latest

    env:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: localhost # default host value for the database
      DB_NAME: djtesting
      DB_PORT: 5432

    services:
      # start a postgres service container
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        # wait until postgres is ready
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: cd app && go build -o ../build/

      - name: Test
        run: cd app && cd migrations && tern migrate && cd .. && go test
